workflows:
  ios-app-store-build:
    name: iOS App Store Build
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.ver1.gdn0"
        XCODE_SCHEME: "gdn0"
        XCODE_PROJECT: "gdn0.xcodeproj"
    scripts:
      - name: Set up keychain
        script: | 
          keychain initialize
      - name: Install certificate
        script: | 
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CERTIFICATE_PASSWORD
      - name: Set up code signing settings
        script: | 
          xcode-project use-profiles
      - name: Build ipa for App Store
        script: | 
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
